GNU CI: show the new error

diff --git a/.github/workflows/GnuTests.yml b/.github/workflows/GnuTests.yml
--- a/.github/workflows/GnuTests.yml
+++ b/.github/workflows/GnuTests.yml
@@ -170,6 +170,8 @@ jobs:
         REPO_DEFAULT_BRANCH='${{ steps.vars.outputs.repo_default_branch }}'
         if test -f "${REF_LOG_FILE}"; then
           echo "Reference SHA1/ID: $(sha1sum -- "${REF_SUMMARY_FILE}")"
+          REF_ERROR=$(sed -n "s/^FAIL: \([[:print:]]\+\).*/\1/p" "${REF_LOG_FILE}" | sort)
+          NEW_ERROR=$(sed -n "s/^FAIL: \([[:print:]]\+\).*/\1/p" '${{ steps.vars.outputs.path_GNU_tests }}/test-suite.log' | sort)
           REF_FAILING=$(sed -n "s/^FAIL: \([[:print:]]\+\).*/\1/p" "${REF_LOG_FILE}" | sort)
           NEW_FAILING=$(sed -n "s/^FAIL: \([[:print:]]\+\).*/\1/p" '${{ steps.vars.outputs.path_GNU_tests }}/test-suite.log' | sort)
           for LINE in ${REF_FAILING}
@@ -186,6 +188,21 @@ jobs:
               have_new_failures="true"
             fi
           done
+          for LINE in ${REF_ERROR}
+          do
+            if ! grep -Fxq ${LINE}<<<"${NEW_ERROR}"; then
+              echo "::warning ::Congrats! The gnu test ${LINE} is no longer ERROR!"
+            fi
+          done
+          for LINE in ${NEW_ERROR}
+          do
+            if ! grep -Fxq ${LINE}<<<"${REF_ERROR}"
+            then
+              echo "::error ::GNU test failed: ${LINE}. ${LINE} is passing on '${{ steps.vars.outputs.repo_default_branch }}'. Maybe you have to rebase?"
+              have_new_failures="true"
+            fi
+          done
+
         else
           echo "::warning ::Skipping test failure comparison; no prior reference test logs are available."
         fi
